export const namespaces = {
  aboutUs: "aboutUs",
  accessibility: "accessibility",
  account: "account",
  accountAuthenticator: "accountAuthenticator",
  accountBugDetails: "accountBugDetails",
  accountBugNew: "accountBugNew",
  accountBugs: "accountBugs",
  accountConsents: "accountConsents",
  accountDelete: "accountDelete",
  accountEmail: "accountEmail",
  accountListings: "accountListings",
  accountListingsEdit: "accountListingsEdit",
  accountListingsNew: "accountListingsNew",
  accountListingsPayments: "accountListingsPayments",
  accountPassword: "accountPassword",
  accountPhoneNumber: "accountPhoneNumber",
  accountProfile: "accountProfile",
  accountSessions: "accountSessions",
  admin: "admin",
  adminBlogPostEdit: "adminBlogPostEdit",
  adminBlogPostNew: "adminBlogPostNew",
  adminBlogPosts: "adminBlogPosts",
  adminBugEdit: "adminBugEdit",
  adminBugs: "adminBugs",
  adminReports: "adminReports",
  archive: "archive",
  common: "common",
  company: "company",
  companyBugs: "companyBugs",
  companyDelete: "companyDelete",
  companyListings: "companyListings",
  companyListingsEdit: "companyListingsEdit",
  companyListingsNew: "companyListingsNew",
  companyListingsPayments: "companyListingsPayments",
  companyPhone: "companyPhone",
  companyProfile: "companyProfile",
  companyProfileEdit: "companyProfileEdit",
  companySettings: "companySettings",
  companyWorker: "companyWorker",
  companyWorkerDelete: "companyWorkerDelete",
  companyWorkerNew: "companyWorkerNew",
  companyWorkerPermissions: "companyWorkerPermissions",
  companyWorkerProfile: "companyWorkerProfile",
  companyWorkers: "companyWorkers",
  contact: "contact",
  emails: "emails",
  flags: "flags",
  help: "help",
  home: "home",
  howToAddListing: "howToAddListing",
  howToSearchListing: "howToSearchListing",
  listing: "listing",
  login: "login",
  modals: "modals",
  notifications: "notifications",
  questions: "questions",
  recoveryAccount: "recoveryAccount",
  recoveryAccountBackupEmail: "recoveryAccountBackupEmail",
  recoveryAccountChangePassword: "recoveryAccountChangePassword",
  registration: "registration",
  registrationAccount: "registrationAccount",
  registrationCompany: "registrationCompany",
  search: "search",
  searchCity: "searchCity",
  seo: "seo",
  sms: "sms",
} as const;

export function getNamespaceValues(): string[] {
  return Object.values(namespaces);
}

export type T_Namespaces = keyof typeof namespaces;
